import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

const lato = Lato({
  weight: '400',
  variable: "--font-lato",
    subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Register Page | EX Game",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable}`}>
        {children}
      </body>
    </html>
  );
}
